---
# tasks file for ansible-apache-role
- name: Install EPEL repo
  package: name=epel-release state=present
  when: ansible_distribution == "CentOS"

- name: download pip script
  get_url:
    url: https://bootstrap.pypa.io/pip/2.7/get-pip.py 
    dest: /tmp/get-pip.py 

- name: install python-pip
  command: python2.7 /tmp/get-pip.py

- name: Install docker python
  pip: name=docker-py

- name: "Copy template index.html to client"
  template:
    src: index.html.j2
    dest: "{{ template_dest }}"

- name: "Create apache container"
  docker_container:
    name: "{{ container_name }}"
    image: httpd
    ports: "{{ exposed_ports }}"
    volumes:
      - "{{ bind_mount }}"