---
    name: Push to Galaxy
    
    on:
      push:
        paths-ignore:
          - 'README.md'
          - 'ansible.cfg'
          - 'inventory.yml'
          - 'files/*'
    
    jobs:
      build:
        runs-on: ubuntu-latest
        steps:
          - name: checkout
            uses: actions/checkout@v3.6.0
          - name: galaxy
            uses: robertdebock/galaxy-action@1.2.1
            with:
              galaxy_api_key: ${{ secrets.GALAXY_API_KEY }}
              git_branch: main